## Overview

This document creates [XML](https://en.wikipedia.org/wiki/XML) files for each turtle shape found in a [NetLogo](https://www.netlogo.org/) XML file (`.nlogox`). Each shape is extracted and saved as a separate XML file in a designated directory.

## Set the Environment

### Load Packages

```{r}
library(cli)
library(here)
library(groomr) # github.com/danielvartan/groomr
library(magick)
library(magrittr)
library(stringr)
library(xml2)
```

### Set Source

```{r}
netlogo_xml_file <- here("nlogox", "netlogo-7-0-3.nlogox")
```

### Set XML Directory

```{r}
xml_dir <- here("xml", "netlogo-7-0-3")
```

```{r}
if (!dir.exists(xml_dir)) {
  dir.create(xml_dir)
}
```

## Import XML Data

```{r}
netlogo_xml <- netlogo_xml_file |> read_xml()
```

## Extract Turtle Shapes

```{r}
turtle_shapes <- netlogo_xml |> xml_find_all("//turtleShapes/shape")
```

## Create XML Shapes

```{r}
cli_progress_bar(
  "Creating XML turtle shapes",
  total = length(turtle_shapes)
)

for (i in seq_along(turtle_shapes)) {
  shape <- turtle_shapes |> extract2(i)
  shape_name <- xml_attr(shape, "name")
  shape_doc <- xml_new_root("turtleShapes")

  xml_add_child(shape_doc, shape)

  filename <-
    shape_name |>
    make_machine_readable() |>
    paste0(".xml")

  filepath <- file.path(xml_dir, filename)

  write_xml(shape_doc, filepath, options = c("format", "no_empty_tags"))

  cli_progress_update()
}

cli_progress_done()
```
